<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Autofac" Version="8.4.0" />
      <PackageReference Include="Carter" Version="9.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="9.0.11" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\PetersPizza.Api.Application.Interfaces\PetersPizza.Api.Application.Interfaces.csproj" />
      <ProjectReference Include="..\PetersPizza.Api.Application\PetersPizza.Api.Application.csproj" />
      <ProjectReference Include="..\PetersPizza.Api.ViewModels\PetersPizza.Api.ViewModels.csproj" />
    </ItemGroup>

</Project>
